name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/checkout@v3
        with:
          repository: 'DeSireFire/animeTrackerList'
          path: animeTrackerList
        
      - uses: actions/checkout@v3
        with:
          repository: 'XIU2/TrackersListCollection'
          path: TrackersListCollection
      
      - name: script
        run: script.sh
      
      - name: update
      - uses: actions/checkout@v3
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generated"
          git push