name: CI

on: 
  push:
  schedule:
    - cron: '30 1,8,16 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/checkout@v3
        with:
          repository: 'DeSireFire/animeTrackerList'
          path: .cache/animeTrackerList
        
      - uses: actions/checkout@v3
        with:
          repository: 'XIU2/TrackersListCollection'
          path: .cache/TrackersListCollection

      - uses: actions/checkout@v3
        with:
          repository: 'ngosang/trackerslist'
          path: .cache/trackerslist
      - uses: actions/checkout@v3

        with:
          repository: 'hezhijie0327/Trackerslist'
          path: .cache/Trackerslist
      
      - name: build
        run: |
          bash script.sh

      - name: config
        run: |
          git config --global user.name "Tunglies"
          git config --global user.email "Tunglies@outlook.com"
          
      - name: update
        run: |
          git add all.txt
          git commit -a -m "update: $(date) total: $(awk NF all.txt | wc -l)"
          git push
